trigger: none 

pool:
  name: 'PRO'

steps:
- task: PowerShell@2
  displayName: 'Monitoring Script for ProLS and ProDR Agent Pool'
  inputs:
    filePath: 'QueueTracker.ps1' 
    arguments: ''
    pwsh: false
  env:
    ProLS_CollectionURL: $(ProLS_CollectionURL)
    ProLS_Project: $(ProLS_Project)
    ProLS_ADO_PAT: $(ProLS_ADO_PAT)
    ProLS_AgentPool: $(ProLS_AgentPool)
    ProLS_Az_SubscriptionID: $(ProLS_Az_SubscriptionID)
    ProLS_Az_TenantID: $(ProLS_Az_TenantID)
    ProLS_Az_ClientID: $(ProLS_Az_ClientID)
    ProLS_Az_Client_Secret: $(ProLS_Az_Client_Secret)
    ProLS_Az_RG: $(ProLS_Az_RG)
    ProLS_Az_VMs: $(ProLS_Az_VMs)

    ProDR_CollectionURL: $(ProDR_CollectionURL)
    ProDR_Project: $(ProDR_Project)
    ProDR_ADO_PAT: $(ProDR_ADO_PAT)
    ProDR_AgentPool: $(ProDR_AgentPool)
    ProDR_Az_SubscriptionID: $(ProDR_Az_SubscriptionID)
    ProDR_Az_TenantID: $(ProDR_Az_TenantID)
    ProDR_Az_ClientID: $(ProDR_Az_ClientID)
    ProDR_Az_Client_Secret: $(ProDR_Az_Client_Secret)
    ProDR_Az_RG: $(ProDR_Az_RG)
    ProDR_Az_VMs: $(ProDR_Az_VMs)
